# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
env:
  secure: "ep+jVex6a77M2pCp4WWTiJRPz6J0dPh848NPZK9jhagvJp1MMW8CVaGnMDD6PB9TEFBKcsTw/fCDyZ2DKrsjqasBdlo+Cn3p8oRByZS7GyIAPaLDgZ/mmmrjn3hQS9CKJUrTf+CAP5zsTdvTkHgdqSNED+b+3AGs0NIyCP5g3ARdJ/rbEh6cVK17saiGn26ZvAHw94gn0CwgNXtaIUemkTv1PcmBoq+toQrODmCMegLF3u3pH5SUd77hjK3ppEyjOIBF0bSweW+3CPOD2PgJP8zE6l6VJbEgdkYvxHeUQctiqgLUWztKZheNEs16495iAvVp2YpwW0JRbRbqZ0QWmzqzWD9NWN/3PwE01Wby/yT043bVCph+aJLMGh7qKauqUmQktAbn5KmsuXLNQnPSGiycycsdtSIAxkbwbqDf0o9UDhhBqWDxAeW4KXTz1kTXo7jhg6bxFnGiHUqyHfnmkeEU5ZxodWkZJj+dQRlbUxJiZyOWtnhapn6m/9ekFO5YNi9LpLs/k4FCNKxDUjmxN7cruT660KE6JD11Y7X6eKUpw6xS2mAd09gNkOihau9guLrbz5tDej7aX20EMqAQPPmIbQw9A92wlJ6cjQJPvBX5n0edSjTf64qioUjGHp5Cusda095hGE9yAv0EMbfzl+XUpGeh3Gw1O8+hmMDTnd0="
r:
  - release
  - devel
